### ISSUE TITLE
Tests fail on ARM hosts due to invalid arguments in the TCG IR during optimization

### ISSUE THREAD

**Issue by NieDzejkob** [unicorn-engine/unicorn#1246]
Steps to reproduce:

1. Get an ARM machine, or set one up with QEMU.
2. Clone the unicorn repository and check out commit `86923806f2431c066dfed33583dab92b9e4e4b9e` (master points to this commit at the time of writing).
3. `make`
4. `cd tests/unit`
5. `make test_x86` (avoid compiling all tests due to the cross-binutils required)
6. `LD_LIBRARY_PATH=../.. ./test_x86`

Output:
```
[==========] Running 12 test(s).
[ RUN      ] test_i386
ERROR: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
test_x86.c:163: error: Failure!

[  FAILED  ] test_i386
[ RUN      ] test_i386_jump
ERROR: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
test_x86.c:216: error: Failure!

[  FAILED  ] test_i386_jump
[ RUN      ] test_i386_inout
ERROR: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
test_x86.c:332: error: Failure!

[  FAILED  ] test_i386_inout
[ RUN      ] test_i386_loop
[       OK ] test_i386_loop
[ RUN      ] test_i386_invalid_mem_read
[       OK ] test_i386_invalid_mem_read
[ RUN      ] test_i386_invalid_mem_write
[       OK ] test_i386_invalid_mem_write
[ RUN      ] test_i386_jump_invalid
[       OK ] test_i386_jump_invalid
[ RUN      ] test_i386_reg_save
Test failed with exception: Segmentation fault

[  FAILED  ] test_i386_reg_save
[ RUN      ] test_x86_64
ERROR: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
test_x86.c:597: error: Failure!

[  FAILED  ] test_x86_64
[ RUN      ] test_x86_64_syscall
ERROR: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
test_x86.c:685: error: Failure!

[  FAILED  ] test_x86_64_syscall
[ RUN      ] test_x86_16
Segmentation fault
```

Through a judicious use of printf, I have traced the error in `test_i386` to [this condition](https://github.com/unicorn-engine/unicorn/blob/709d0819722abec2f34786c131d92b5d2093dc1e/qemu/tcg/optimize.c#L574) firing:

```
[ RUN      ] test_i386
TCG_MAX_TEMPS exceeded: args[i] = 4294967295, i = 3, nb_oargs = 0, nb_iargs = 6, op = 8, op_index = 5, nb_ops = 81, def->name = "call"
```

**Comment by NieDzejkob** [comment]
Note that, while I have phrased this as a test failure, similar nonsensical results can be seen when running any code using the library on 32-bit ARM.

**Comment by aquynh** [comment]
can you do this quick test: try with older version v1.0.1?

**Comment by NieDzejkob** [comment]
Good question - v1.0.1 works. I have commenced a git bisect.

**Comment by aquynh** [comment]
cool, let us know which commit breaks it.
and pull req if you can, thanks.

**Comment by NieDzejkob** [comment]
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
b0ae2138fb73daedafdc4b4d9315e6294971b2d9
1aaf57ca543de56282b42d96786527db90860e2c
1fea4e6d87826fcf84a5373fc29b078061c6232a
92392e0f572a1a3cb43f0f63d4183cc4b2b37173
f4b375c65189491e5b27dc5a3e1a3689eb899477
5c7c8375f987474ae43cff8e20b83c80effc0192
fac6a6686020c6b27e0e44425c38a17d7ca1adfe
002151874a78c991f41fbe9d16a9f4d6e97ee959
8840d5b42b92c75d802741baab9b4437e762e8c8
00ca6b1a5f4c8bf999385aa08c08fb6d58b5b638
1aeaf5c40d8348a11b1eb31550633a9167d26f40
429bfca48e06c08cda5065755253017d2cdbefc9
We cannot bisect more!
```
For some reason, these commits error out at `PRId64`

**Comment by aquynh** [comment]
@NieDzejkob please confirm this is now fixed.

**Comment by NieDzejkob** [comment]
I have confirmed that the tests are now passing.
